import type { NextPage } from 'next'

import Head from 'next/head'
import NextLink from 'next/link'
import { Fragment } from 'react'
import { Button, Container, Flex, Heading, Input, Link } from '@chakra-ui/react'
import { ArrowBackIcon } from '@chakra-ui/icons'

import { Header } from '../components/Header'

const ForgetPassword: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Ebuy | Recuperar senha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container 
        maxW="container.xl" 
        height="calc(100vh - 93px)"
        display="flex" 
        alignItems="center" 
        justifyContent="center"
      >
        <Flex
          width="96"
          height="96"
          padding="8"
          flexDirection="column"
          borderRadius="lg"
          backgroundColor="blackAlpha.200"
        >
          <NextLink href="/login" passHref>
            <Link display="absolute" top="32px">
              <ArrowBackIcon h={6} w={6} />
            </Link>
          </NextLink>
          <Flex
            height="full"
            flexDirection="column"
            justifyContent="center"
            gap="2"
          >
            <Heading
              as="h2"
              fontSize="2xl"
              marginBottom="4"
            >
              Recuperar senha
            </Heading>
            <Input 
              type="email"
              placeholder="Digite seu email"
              backgroundColor="white"
            />
            <Button
              width="full"
              colorScheme="blackAlpha"
            >ENVIAR</Button>
          </Flex>
        </Flex>
      </Container>
    </Fragment>
  )
}

export default ForgetPassword
