import type { NextPage } from 'next'

import Head from 'next/head'
import NextLink from 'next/link'
import { FormEvent, Fragment, useRef } from 'react'
import { Button, Container, Flex, Heading, Input, Link } from '@chakra-ui/react'
import { ArrowBackIcon } from '@chakra-ui/icons'

import { Header } from '../components/Header'

const ForgotPassword: NextPage = () => {
  const emailRef = useRef<HTMLInputElement>(null)

  function onSubmitForgotPassword(event: FormEvent) {
    event.preventDefault()

    if (!emailRef.current) return

    const { value: email } = emailRef.current

    if (email === '') return

    console.log({
      email
    })
  }

  return (
    <Fragment>
      <Head>
        <title>Ebuy | Recuperar senha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container 
        maxW="container.xl" 
        height="calc(100vh - 93px)"
        display="flex" 
        alignItems="center" 
        justifyContent="center"
      >
        <Flex
          width="96"
          height="96"
          padding="8"
          flexDirection="column"
          borderRadius="lg"
          backgroundColor="blackAlpha.200"
        >
          <NextLink href="/login" passHref>
            <Link display="absolute" top="32px">
              <ArrowBackIcon h={6} w={6} />
            </Link>
          </NextLink>
          <Flex
            height="full"
            flexDirection="column"
            justifyContent="center"
          >
            <Heading
              as="h2"
              fontSize="2xl"
              marginBottom="4"
            >
              Recuperar senha
            </Heading>
            <form onSubmit={onSubmitForgotPassword}>
              <Input 
                ref={emailRef}
                type="email"
                placeholder="Digite seu email"
                backgroundColor="white"
              />
              <Button
                type="submit"
                width="full"
                marginTop="2"
                colorScheme="blackAlpha"
              >ENVIAR</Button>
            </form>
          </Flex>
        </Flex>
      </Container>
    </Fragment>
  )
}

export default ForgotPassword
