import type { GetStaticProps, NextPage } from 'next'

import Head from 'next/head'
import { Fragment } from 'react'
import { Container, SimpleGrid } from '@chakra-ui/react'

import { fakeProducts } from './api/products'
import { Product } from '../components/Product'

interface SSG {
  products: Array<{
    id: string
    image: string
    name: string
    price: number
  }>
}

const Home: NextPage<SSG> = ({ products }) => {
  return (
    <Fragment>
      <Head>
        <title>Ebuy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container 
        marginY="4"
        maxW="container.lg"
      >
        <SimpleGrid 
          marginX="auto"
          justifyItems="center"
          minChildWidth="240px"
          spacing="16"
        >
          { products.map(({ id, image, name, price }) => (
              <Product 
                key={id}
                image={image}
                name={name}
                price={price}
              />
            ))
          }
        </SimpleGrid>
      </Container>
    </Fragment>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      products: fakeProducts
    }
  }
}

export default Home
