import type { NextPage } from 'next'

import Head from 'next/head'
import NextLink from 'next/link'
import { Fragment } from 'react'
import { Button, Container, Flex, Heading, Input, Link } from '@chakra-ui/react'

import { Header } from '../components/Header'

const Login: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Ebuy | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container 
        maxW="container.xl" 
        height="calc(100vh - 93px)"
        display="flex" 
        alignItems="center" 
        justifyContent="center"
      >
        <Flex
          width="96"
          height="96"
          padding="8"
          flexDirection="column"
          justifyContent="center"
          gap="2"
          borderRadius="lg"
          backgroundColor="blackAlpha.200"
        >
          <Flex marginBottom="4" justifyContent="space-between">
            <Heading
              as="h2"
              fontSize="2xl"
            >
              Login
            </Heading>
            <NextLink href="/sigin" passHref>
              <Link color="blue.500">
                Criar conta
              </Link>
            </NextLink>
          </Flex>
          <Input 
            type="email"
            placeholder="Digite seu email"
            backgroundColor="white"
          />
          <Input 
            type="password"
            placeholder="Digite sua senha"
            backgroundColor="white"
          />
          <Button
            width="full"
            colorScheme="blackAlpha"
          >ENTRAR</Button>
          <NextLink href="/forgot-password" passHref>
            <Link color="blue.500" textAlign="center" marginTop="4">
              Esqueci minha senha
            </Link>
          </NextLink>
        </Flex>
      </Container>
    </Fragment>
  )
}

export default Login
