import type { NextPage } from 'next'

import Head from 'next/head'
import NextLink from 'next/link'
import { Fragment } from 'react'
import { Button, Container, Flex, Heading, Input, Link } from '@chakra-ui/react'
import { ArrowBackIcon } from '@chakra-ui/icons'

import { Header } from '../components/Header'

const Sigin: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Ebuy | Criar conta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container 
        maxW="container.xl" 
        height="calc(100vh - 93px)"
        display="flex" 
        alignItems="center" 
        justifyContent="center"
      >
        <Flex
          width="96"
          height="96"
          padding="8"
          flexDirection="column"
          borderRadius="lg"
          backgroundColor="blackAlpha.200"
        >
          <NextLink href="/login" passHref>
            <Link display="absolute" top="32px">
              <ArrowBackIcon h={6} w={6} />
            </Link>
          </NextLink>
          <Flex
            height="full"
            flexDirection="column"
            justifyContent="center"
            gap="2"
          >
            <Flex marginBottom="4" justifyContent="space-between">
              <Heading
                as="h2"
                fontSize="2xl"
              >
                Criar conta
              </Heading>
              <NextLink href="/login" passHref>
                <Link href="#" color="blue.500">
                  Logar
                </Link>
              </NextLink>
            </Flex>
            <Input 
              type="text"
              placeholder="Digite seu nome"
              backgroundColor="white"
            />
            <Input 
              type="email"
              placeholder="Digite um email"
              backgroundColor="white"
            />
            <Input 
              type="password"
              placeholder="Digite uma senha"
              backgroundColor="white"
            />
            <Button
              width="full"
              colorScheme="blackAlpha"
            >CADASTRAR</Button>
          </Flex>
        </Flex>
      </Container>
    </Fragment>
  )
}

export default Sigin
